"""Initial migration

Revision ID: b14d3e22e5df
Revises: 2cd371b70158
Create Date: 2025-09-17 10:54:07.731102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14d3e22e5df'
down_revision: Union[str, Sequence[str], None] = '2cd371b70158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_secteurs_id'), 'secteurs', ['id'], unique=False)
    op.create_table('normes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codification', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('fichier_pdf', sa.String(length=255), nullable=False),
    sa.Column('secteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codification')
    )
    op.create_index(op.f('ix_normes_id'), 'normes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normes_id'), table_name='normes')
    op.drop_table('normes')
    op.drop_index(op.f('ix_secteurs_id'), table_name='secteurs')
    op.drop_table('secteurs')
    # ### end Alembic commands ###
